// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3WY88b1BFGtOdpAPLIg7TJGpMiWr7Z78',
    appId: '1:761899928359:web:e3ec3dc2f92d80ce17b702',
    messagingSenderId: '761899928359',
    projectId: 'my-app-haffeli',
    authDomain: 'my-app-haffeli.firebaseapp.com',
    storageBucket: 'my-app-haffeli.appspot.com',
    measurementId: 'G-RSQ9RCKXZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRw-qX-jSSOh9oZyV5RLG4orGzt8iW9A',
    appId: '1:761899928359:android:8036670b9128f17317b702',
    messagingSenderId: '761899928359',
    projectId: 'my-app-haffeli',
    storageBucket: 'my-app-haffeli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCui164ls_een3-BiLXH07uTY2vLtgTNHY',
    appId: '1:761899928359:ios:ed4a56ee690c4e0917b702',
    messagingSenderId: '761899928359',
    projectId: 'my-app-haffeli',
    storageBucket: 'my-app-haffeli.appspot.com',
    androidClientId: '761899928359-9eei3utlts186it1atoogccicjhn2vo1.apps.googleusercontent.com',
    iosClientId: '761899928359-hgkvqrotvqmreqfl03btuirkbnneu9nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectHaffeli',
  );
}
